index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

signup:
    path: /signup
    controller: App\Controller\UserController::register

signin:
    path: /signin
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

catalog:
    path: /catalog
    methods: GET
    controller: App\Controller\StorefrontController::index

create_product:
    path: /product/create
    controller: App\Controller\ProductController::create

order:
    path: /order/{productId}
    methods: GET
    controller: App\Controller\OrderForm::index

history:
    path: /order/list/all
    methods: GET
    controller: App\Controller\OrderHistory::history

delete_product:
    path: /product/{productId}/delete
    methods: POST
    controller: App\Controller\StorefrontController::deleteProduct