index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

signup:
    path: /signup
    controller: App\Controller\UserController::register

signin:
    path: /signin
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

catalog:
    path: /catalog
    methods: GET
    controller: App\Controller\StorefrontController::index

order:
    path: /order/{productId}
    methods: GET
    controller: App\Controller\OrderForm::index