index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

register:
    path: /register
    methods: POST
    controller: App\Controller\UserController::createUser

catalog:
    path: /catalog
    methods: GET
    controller: App\Controller\StorefrontController::index